# Generated by Django 2.2 on 2019-04-27 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auteur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
