# Generated by Django 2.2 on 2019-04-28 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auteur', '0005_auto_20190427_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='auteur',
            unique_together={('user', 'prenom', 'nom')},
        ),
    ]
